# Generated by Django 2.1.2 on 2018-12-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20181208_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.PositiveSmallIntegerField(choices=[(1, 'BTP'), (2, 'Honours')], default=1)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Student')),
            ],
        ),
    ]
